services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: your_SO-desktop # El nombre que verá tu teléfono
    environment:
      - PUID=1000
      - PGID=1000
      - Your_Wifi_Name=Country/City
    volumes:
      - ./config:/config
      - /home/user/backup_folder/data1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
